# =============================================================================
# JVP Website - Cloudflare Worker Configuration
# =============================================================================

name = "jvp"
compatibility_date = "2025-01-31"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"
